"""Check source reconciliation, cardinality, foreign keys, and data quality."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from app.database.verify import verify_database, verification_markdown


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--database', type=Path, default=ROOT / 'data/processed/olist.sqlite')
    parser.add_argument('--raw-dir', type=Path, default=ROOT / 'data/raw')
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'docs/generated')
    args = parser.parse_args()
    report = verify_database(args.database, args.raw_dir)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / 'verification_report.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    (args.output_dir / 'verification_report.md').write_text(verification_markdown(report), encoding='utf-8')
    metrics = ['# Measured project metrics', '', 'Phase 1 only. Regenerated by `scripts/verify_database.py`.', '',
               f"- Source CSVs / database tables: {len(report['source_files'])} / {len(report['source_files'])}.",
               f"- Source and loaded records: {sum(t['rows'] for t in report['source_files'].values()):,} (includes original duplicates).",
               f"- Database checks passed: {sum(c['passed'] for c in report['checks'])}/{len(report['checks'])}.",
               '- Six join/cardinality checks; three exact monetary reconciliations against CSV Decimal sums.',
               '- LLM execution accuracy, answer accuracy, retrieval accuracy, latency improvement and cost: not measured; later phases.',
               '- Evaluation questions: not yet implemented. Database checks are not an LLM benchmark.', '',
               'Evidence: [verification report](generated/verification_report.md), [machine-readable evidence](generated/verification_report.json).', '']
    # Keep custom report runs self-contained; write resume metrics only for the default project reports.
    if args.output_dir.resolve() == (ROOT / 'docs/generated').resolve():
        (ROOT / 'docs/project_metrics.md').write_text('\n'.join(metrics), encoding='utf-8')
    print(f"Passed {sum(c['passed'] for c in report['checks'])}/{len(report['checks'])} checks.")
    if not report['all_checks_passed']:
        raise SystemExit(1)


if __name__ == '__main__':
    main()
